using System.Reflection.Metadata;

namespace DapperNpa.SourceGenerator;

internal sealed partial class RepositorySourceGenerator
{
    private static readonly string RepositoryImplementationTemplate = 
    $$"""
        // <auto-generated/>
        // {{DateTime.Now}}
        #nullable enable

        using Dapper;

        namespace __NAMESPACE__
        {
            internal sealed class __CLASS__ : global::__INTERFACE___
            {
                private readonly global::System.Data.IDbConnection _connection;
                public __CLASS__(global::System.Data.IDbConnection connection)
                {
                    _connection = connection;
                }

                #region Generated implementation methods
                __IMPLEMENTATION_METHODS__
                #endregion
            }
        }
    """;
    private static readonly string MethodImplementationTemplate = 
    $$"""
        // <auto-generated/>
        //{{DateTime.Now}}
        __MODIFIER__ __RETURNTYPE__ __IDENTIFIER__(__PARAMETERS__)
        {
            __RETURNKEYWORD__ _connection.__QUERYMETHOD____RESULTRETURNTYPE__(__SQLIMPLEMENTATION__)__RETURN_RESULT__;
        }
    """;
}