namespace DapperNpa.SourceGenerator;

internal sealed partial class RepositorySourceGenerator
{
    private static string RepositoryImplementationTemplate = $$"""
// <auto-generated/>
// {{DateTime.Now}}
#nullable enable

namespace __NAMESPACE__
{
    internal sealed class __CLASS__ : global::__INTERFACE___
    {
        private readonly global::System.Data.IDbConnection _connection;
        public __CLASS__(global::System.Data.IDbConnection connection)
        {
            _connection = connection;
        }

        #region Generated implementation methods
        __IMPLEMENTATION_METHODS__
        #endregion
    }
}
""";
}